version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bird_backend_dev
      - POSTGRES_PASSWORD=bird_backend_dev
      - POSTGRES_DB=bird_backend_db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app_data:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    depends_on:
      - db

volumes:
  postgres_data:
  app_data: